# Setup
title:               Jorg Eikens
tagline:             'Designer and Thinkerer'
description:         'My journey so far ...'
url:                 http://localhost:4000
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jorg Eikens
  url:               https://jorg.eikens.com
  email:             jorg@eikens.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
# version:             1.1.0
google_analytics_id: #UA-XXXX-Y
